name: Build and deploy container app to Azure Web App - reserveit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://upbimages.azurecr.io/
        username: upbimages
        password: uViuLYImNy0PhEeuTpFwok4TM20aOjLBOVneUv7nfj+ACRAUWdYI

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: upbimages.azurecr.io/reserveit:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reserveit'
        slot-name: 'production'
        publish-profile: '<publishData><publishProfile profileName="reserveit - Web Deploy" publishMethod="MSDeploy" publishUrl="reserveit.scm.azurewebsites.net:443" msdeploySite="reserveit" userName="$reserveit" userPWD="ywefEJZ7Z8g5Boqbzd1Kb0nLnhKrf4nherpQtAmKB4TmixyyFlLhx7p3BnYG" destinationAppUrl="https://reserveit.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="reserveit - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-plc-003.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="reserveit\$reserveit" userPWD="ywefEJZ7Z8g5Boqbzd1Kb0nLnhKrf4nherpQtAmKB4TmixyyFlLhx7p3BnYG" destinationAppUrl="https://reserveit.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="reserveit - Zip Deploy" publishMethod="ZipDeploy" publishUrl="reserveit.scm.azurewebsites.net:443" userName="$reserveit" userPWD="ywefEJZ7Z8g5Boqbzd1Kb0nLnhKrf4nherpQtAmKB4TmixyyFlLhx7p3BnYG" destinationAppUrl="https://reserveit.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
        images: 'upbimages.azurecr.io/reserveit:${{ github.sha }}'
